//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisDetaylari
    {
        public int id { get; set; }
        public int SatisNo { get; set; }
        public int UrunNo { get; set; }
        public int Adet { get; set; }
        public decimal BirimFiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Satislar Satislar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
