//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slaytlar
    {
        public int SlaytId { get; set; }
        public string SlaytResimYolu { get; set; }
        public string SlaytUstYazi { get; set; }
        public string SlaytOrtaYazi { get; set; }
        public string SlaytAltYazi { get; set; }
        public bool Silindi { get; set; }
    }
}
