//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SatisDetaylari = new HashSet<SatisDetaylari>();
        }
    
        public int UrunId { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAd { get; set; }
        public int UrunKategoriNo { get; set; }
        public int UrunAltKategoriNo { get; set; }
        public int UrunAltAltKategoriNo { get; set; }
        public int UrunMiktar { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunAciklama { get; set; }
        public string UrunResim1 { get; set; }
        public string UrunResim2 { get; set; }
        public string UrunResim3 { get; set; }
        public string UrunResim4 { get; set; }
        public string UrunBedenAdi { get; set; }
        public string UrunRenkAdi { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisDetaylari> SatisDetaylari { get; set; }
    }
}
